pub mod chunking;
pub mod code_index;
pub mod colbert;
pub mod compact;
pub mod consolidation;
pub mod context;
pub mod contradiction;
pub mod domain;
pub mod embeddings;
pub mod evolution;
pub mod health;
pub mod hyde;
pub mod ingest;
pub mod learner;
pub mod llm;
pub mod optimizer;
pub mod raptor;
pub mod reflection;
pub mod tool_mining;

pub use colbert::ColbertService;
pub use compact::{CompactRestoreResult, CompactRestorer};
pub use consolidation::{ConsolidationPipeline, ConsolidationReport};
pub use context::{ContextInjector, ContextResult};
pub use contradiction::{ContradictionDetector, ContradictionResult};
pub use domain::{ContentDomain, detect_domain};
pub use embeddings::EmbeddingService;
pub use hyde::HydeGenerator;
pub use ingest::ContentIngester;
pub use learner::SessionLearner;
pub use llm::LlmClient;
pub use optimizer::{ContextOptimizer, OptimizeResult};
pub use raptor::RaptorBuilder;
pub use reflection::{ReflectionActionItem, ReflectionData, ReflectionGenerator};
pub use tool_mining::ToolSequenceMiner;
