use alaz_core::models::{ListCoreMemoryFilter, ListEpisodesFilter, ListProceduresFilter};
use alaz_db::repos::{CoreMemoryRepo, EpisodeRepo, ProcedureRepo, ProjectRepo};
use anyhow::Result;
use sqlx::PgPool;

/// A section of the generated CLAUDE.md, with a priority (lower = more important).
struct Section {
    priority: u8,
    heading: &'static str,
    body: String,
}

/// Query the Alaz database and assemble a project-specific CLAUDE.md body.
pub async fn generate_claude_md(pool: &PgPool, project: &str, max_chars: usize) -> Result<String> {
    // Resolve project name → project ID (repos filter by ID, not name)
    let project_id = ProjectRepo::get_by_name(pool, project)
        .await
        .ok()
        .flatten()
        .map(|p| p.id);
    let pid = project_id.as_deref().unwrap_or("");

    // Gather all sections concurrently
    let (constraints, facts, conventions, preferences, issues, procedures, health) = tokio::join!(
        build_core_memory_section(pool, pid, "constraint"),
        build_core_memory_section(pool, pid, "fact"),
        build_core_memory_section(pool, pid, "convention"),
        build_core_memory_section(pool, pid, "preference"),
        build_issues_section(pool, pid),
        build_procedures_section(pool, pid),
        build_health_section(pool, pid),
    );

    let mut sections = vec![
        Section {
            priority: 0,
            heading: "Critical Rules",
            body: constraints.unwrap_or_default(),
        },
        Section {
            priority: 1,
            heading: "Project Info",
            body: facts.unwrap_or_default(),
        },
        Section {
            priority: 2,
            heading: "Conventions",
            body: conventions.unwrap_or_default(),
        },
        Section {
            priority: 3,
            heading: "Preferences",
            body: preferences.unwrap_or_default(),
        },
        Section {
            priority: 4,
            heading: "Active Issues",
            body: issues.unwrap_or_default(),
        },
        Section {
            priority: 5,
            heading: "Key Procedures",
            body: procedures.unwrap_or_default(),
        },
        Section {
            priority: 7,
            heading: "Knowledge Health",
            body: health.unwrap_or_default(),
        },
        Section {
            priority: 8,
            heading: "Alaz Usage",
            body: build_usage_section(),
        },
    ];

    // P3.5: Cross-project intelligence
    let project_dir = std::env::current_dir().unwrap_or_default();
    let tech_stack = detect_tech_stack(&project_dir);
    sections.push(
        build_cross_project_section(
            pool,
            if pid.is_empty() { None } else { Some(pid) },
            &tech_stack,
        )
        .await?,
    );

    // Sort by priority (most important first)
    sections.sort_by_key(|s| s.priority);

    // Assemble with token budget
    let header = format!(
        "# {} \u{2014} Alaz Context\n\n_Auto-generated by `alaz generate-claude-md` on {}_\n",
        project,
        chrono::Utc::now().format("%Y-%m-%d %H:%M UTC"),
    );

    let mut output = header;
    for section in &sections {
        if section.body.is_empty() {
            continue;
        }
        let block = format!("\n## {}\n\n{}\n", section.heading, section.body);
        if output.len() + block.len() > max_chars {
            // Try to fit a truncated version
            let remaining = max_chars.saturating_sub(output.len() + 20); // 20 for heading + ellipsis
            if remaining > 80 {
                let heading_line = format!("\n## {}\n\n", section.heading);
                let avail = max_chars.saturating_sub(output.len() + heading_line.len() + 10);
                let safe_end = section
                    .body
                    .floor_char_boundary(avail.min(section.body.len()));
                output.push_str(&heading_line);
                output.push_str(&section.body[..safe_end]);
                output.push_str("\n...\n");
            }
            break;
        }
        output.push_str(&block);
    }

    Ok(output)
}

/// Build a core-memory section for a given category.
/// Queries both project-scoped and global memories.
async fn build_core_memory_section(pool: &PgPool, project: &str, category: &str) -> Result<String> {
    // Project-scoped memories
    let project_memories = CoreMemoryRepo::list(
        pool,
        &ListCoreMemoryFilter {
            project: Some(project.to_string()),
            category: Some(category.to_string()),
            limit: Some(30),
            ..Default::default()
        },
    )
    .await
    .unwrap_or_default();

    // Global memories (project_id IS NULL)
    let global_memories = CoreMemoryRepo::list_global(pool, 30)
        .await
        .unwrap_or_default()
        .into_iter()
        .filter(|m| m.category == category)
        .collect::<Vec<_>>();

    if project_memories.is_empty() && global_memories.is_empty() {
        return Ok(String::new());
    }

    let mut lines = Vec::new();

    for mem in &project_memories {
        lines.push(format!("- **{}**: {}", mem.key, mem.value));
    }

    for mem in &global_memories {
        lines.push(format!("- **{}** _(global)_: {}", mem.key, mem.value));
    }

    Ok(lines.join("\n"))
}

/// Build the active-issues section from unresolved episodes.
async fn build_issues_section(pool: &PgPool, project: &str) -> Result<String> {
    let episodes = EpisodeRepo::list(
        pool,
        &ListEpisodesFilter {
            project: Some(project.to_string()),
            resolved: Some(false),
            limit: Some(15),
            ..Default::default()
        },
    )
    .await
    .unwrap_or_default();

    if episodes.is_empty() {
        return Ok(String::new());
    }

    // Filter out superseded episodes, then sort by severity: critical > high > medium > low > none
    let mut sorted: Vec<_> = episodes
        .into_iter()
        .filter(|e| e.superseded_by.is_none())
        .collect();
    if sorted.is_empty() {
        return Ok(String::new());
    }
    sorted.sort_by(|a, b| {
        severity_rank(a.severity.as_deref()).cmp(&severity_rank(b.severity.as_deref()))
    });

    let lines: Vec<String> = sorted
        .iter()
        .map(|ep| {
            let severity_tag = ep
                .severity
                .as_deref()
                .map(|s| format!("[{s}] "))
                .unwrap_or_default();
            let truncated_content = truncate_str(&ep.content, 150);
            format!("- {severity_tag}**{}**: {truncated_content}", ep.title)
        })
        .collect();

    Ok(lines.join("\n"))
}

/// Build the key-procedures section.
async fn build_procedures_section(pool: &PgPool, project: &str) -> Result<String> {
    let procedures = ProcedureRepo::list(
        pool,
        &ListProceduresFilter {
            project: Some(project.to_string()),
            limit: Some(30),
            ..Default::default()
        },
    )
    .await
    .unwrap_or_default();

    // Filter: not superseded, utility_score >= 0.05
    let filtered: Vec<_> = procedures
        .into_iter()
        .filter(|p| p.superseded_by.is_none() && p.utility_score >= 0.05)
        .collect();

    if filtered.is_empty() {
        return Ok(String::new());
    }

    // Sort by utility_score descending, take top 10
    let mut sorted = filtered;
    sorted.sort_by(|a, b| {
        b.utility_score
            .partial_cmp(&a.utility_score)
            .unwrap_or(std::cmp::Ordering::Equal)
    });
    sorted.truncate(10);

    let lines: Vec<String> = sorted
        .iter()
        .map(|proc| {
            let score = format!("{:.0}%", proc.success_rate.unwrap_or(0.0) * 100.0);
            let truncated = truncate_str(&proc.content, 300);
            format!("- **{}** (success: {score}): {truncated}", proc.title)
        })
        .collect();

    Ok(lines.join("\n"))
}

/// Run a single COUNT(*) query and return the count (or 0 on error).
async fn count_query(pool: &PgPool, sql: &str, project: &str) -> i64 {
    #[derive(sqlx::FromRow)]
    struct Count {
        count: i64,
    }
    sqlx::query_as::<_, Count>(sql)
        .bind(Some(project))
        .fetch_one(pool)
        .await
        .map(|c| c.count)
        .unwrap_or(0)
}

/// Build knowledge health stats via direct count queries.
async fn build_health_section(pool: &PgPool, project: &str) -> Result<String> {
    let (ka, ks, et, eu, pa, cm) = tokio::join!(
        count_query(
            pool,
            "SELECT COUNT(*) as count FROM knowledge WHERE ($1::TEXT IS NULL OR project_id = $1) AND superseded_by IS NULL",
            project
        ),
        count_query(
            pool,
            "SELECT COUNT(*) as count FROM knowledge WHERE ($1::TEXT IS NULL OR project_id = $1) AND superseded_by IS NOT NULL",
            project
        ),
        count_query(
            pool,
            "SELECT COUNT(*) as count FROM episodes WHERE ($1::TEXT IS NULL OR project_id = $1)",
            project
        ),
        count_query(
            pool,
            "SELECT COUNT(*) as count FROM episodes WHERE ($1::TEXT IS NULL OR project_id = $1) AND resolved = FALSE",
            project
        ),
        count_query(
            pool,
            "SELECT COUNT(*) as count FROM procedures WHERE ($1::TEXT IS NULL OR project_id = $1) AND superseded_by IS NULL",
            project
        ),
        count_query(
            pool,
            "SELECT COUNT(*) as count FROM core_memories WHERE ($1::TEXT IS NULL OR project_id = $1) OR project_id IS NULL",
            project
        ),
    );

    Ok(format!(
        "| Metric | Count |\n\
         |--------|-------|\n\
         | Knowledge entries (active) | {ka} |\n\
         | Knowledge entries (superseded) | {ks} |\n\
         | Episodes (total) | {et} |\n\
         | Episodes (unresolved) | {eu} |\n\
         | Procedures (active) | {pa} |\n\
         | Core memories | {cm} |"
    ))
}

/// Static Alaz usage instructions section.
fn build_usage_section() -> String {
    "\
Use Alaz tools for all memory operations during this session:

- `alaz_search` / `alaz_hybrid_search` -- find knowledge, patterns, decisions
- `alaz_save` -- persist new discoveries, patterns, architecture decisions
- `alaz_core_memory` -- manage persistent facts, preferences, conventions, constraints
- `alaz_episodes` -- view notable events (errors, decisions, successes)
- `alaz_procedures` -- access step-by-step guides with confidence scores
- `alaz_cue_search` -- 5W cue-based recall (who/what/where/when/why)

**Do NOT use file-based memory (MEMORY.md).** Alaz IS the memory system."
        .to_string()
}

/// Detect the project's tech stack by checking for well-known files.
pub fn detect_tech_stack(project_dir: &std::path::Path) -> Vec<String> {
    let checks: &[(&str, &str)] = &[
        ("package.json", "node.js"),
        ("next.config.js", "next.js"),
        ("next.config.ts", "next.js"),
        ("next.config.mjs", "next.js"),
        ("prisma/schema.prisma", "prisma"),
        ("Cargo.toml", "rust"),
        ("docker-compose.yml", "docker"),
        ("docker-compose.yaml", "docker"),
        ("Dockerfile", "docker"),
        ("flake.nix", "nixos"),
        ("requirements.txt", "python"),
        ("pyproject.toml", "python"),
        ("go.mod", "go"),
        ("tsconfig.json", "typescript"),
    ];

    let mut stack = Vec::new();
    for &(file, tech) in checks {
        if project_dir.join(file).exists() && !stack.contains(&tech.to_string()) {
            stack.push(tech.to_string());
        }
    }
    stack
}

/// Build a cross-project knowledge section by finding projects with overlapping tech stacks.
async fn build_cross_project_section(
    pool: &PgPool,
    current_project_id: Option<&str>,
    current_tech_stack: &[String],
) -> Result<Section> {
    if current_tech_stack.is_empty() {
        return Ok(Section {
            heading: "Related Knowledge (Other Projects)",
            body: String::new(),
            priority: 6,
        });
    }

    let projects = ProjectRepo::list(pool).await.unwrap_or_default();
    let mut body = String::new();
    let mut items_added = 0usize;
    let max_items = 5;

    for project in &projects {
        if current_project_id == Some(project.id.as_str()) {
            continue;
        }
        if items_added >= max_items {
            break;
        }

        // Check tech stack overlap via core memories
        let filter = ListCoreMemoryFilter {
            category: Some("fact".to_string()),
            project: Some(project.id.clone()),
            limit: Some(50),
            ..Default::default()
        };
        let memories = CoreMemoryRepo::list(pool, &filter)
            .await
            .unwrap_or_default();
        let has_overlap = memories.iter().any(|m| {
            let lower = m.value.to_lowercase();
            current_tech_stack.iter().any(|tech| lower.contains(tech))
        });

        if !has_overlap {
            continue;
        }

        // Get notable episodes from this project
        let ep_filter = ListEpisodesFilter {
            project: Some(project.id.clone()),
            kind: Some("error".to_string()),
            limit: Some(3),
            ..Default::default()
        };
        let episodes = EpisodeRepo::list(pool, &ep_filter)
            .await
            .unwrap_or_default();

        for ep in episodes.iter().take(2) {
            if items_added >= max_items {
                break;
            }
            let snippet = truncate_str(&ep.content, 120);
            use std::fmt::Write;
            let _ = writeln!(body, "- **{}** ({}): {}", ep.title, project.name, snippet);
            items_added += 1;
        }
    }

    Ok(Section {
        heading: "Related Knowledge (Other Projects)",
        body,
        priority: 6,
    })
}

/// Truncate a string to at most `max_len` characters, appending "..." if truncated.
/// Uses `floor_char_boundary` for UTF-8 safety.
fn truncate_str(s: &str, max_len: usize) -> String {
    if s.len() <= max_len {
        return s.to_string();
    }
    let boundary = s.floor_char_boundary(max_len);
    format!("{}...", &s[..boundary])
}

/// Map severity strings to a numeric rank for sorting (lower = more severe).
fn severity_rank(severity: Option<&str>) -> u8 {
    match severity {
        Some("critical") => 0,
        Some("high") => 1,
        Some("medium") => 2,
        Some("low") => 3,
        _ => 4,
    }
}
