ALTER TABLE episodes ADD COLUMN IF NOT EXISTS action TEXT;
ALTER TABLE episodes ADD COLUMN IF NOT EXISTS outcome TEXT;
ALTER TABLE episodes ADD COLUMN IF NOT EXISTS outcome_score DOUBLE PRECISION;
ALTER TABLE episodes ADD COLUMN IF NOT EXISTS related_files TEXT[] DEFAULT '{}';
